### ISSUE TITLE
Define poverty

### ISSUE THREAD

**Issue by unitof** [MKorostoff/1-pixel-wealth#20]
https://github.com/MKorostoff/1-pixel-wealth/blob/b965f2d9cf39db03a885717e1c5d8a17cee5eb5e/index.html#L467

I think it’d be nice to add or link to the definition of poverty this stat uses. Is it just an annual income threshold? Happy to write it if someone can point me to the source.

**Comment by MKorostoff** [comment]
I'm referring here to the federal poverty threshold. You can read the formula here https://aspe.hhs.gov/poverty-guidelines. 

There's already a census document linked on the website with a very in depth discussion of poverty. I use links and asides sparingly, because they interrupt the flow. I think a formal definition of poverty is easy enough to find through Google, I don't think it warrants it's own link here. See my reply on issue #3 for more on the rationale here. Thanks for the suggestion though.
