### ISSUE TITLE
CITATIONS!

### ISSUE THREAD

**Issue by xirianlight** [MKorostoff/1-pixel-wealth#3]
Freaking bless you for making this, this project is an incredible way to communicate this information. Well done.

Any chance you can cite more of your statements? As someone who probably holds beliefs similar to you, I'm easy to sway, but for people who may check this out just to poke holes in it and own the libs, the more citations and external references you can backlink, the better. 

Seriously. Well done.

**Comment by MKorostoff** [comment]
Thanks! You know, I actually had an earlier version of this project where each assertion was followed by a numbered citation, which you could click to pop-up an "about" modal, where you could read about not just the original source of the data, but also the methodology I used to arrive at a specific claim. The main reasons I removed this feature are:

1. I felt it invited a lot of distracting debate about numbers that cannot be known exactly. Billionaire defenders will just "well ACTUALLY..." any methodology I use, thinking it discredits the whole project. They'll spend all of their energy trying to "prove" that malaria eradication does not cost 3% of superwealth, but instead costs 5.2% (as if that changed the ultimate policy conclusion at all). Supporters, in turn, will spend all of their energy trying prove the opposite. This is not what I want. I want people to gain a gut-level understanding of the magnitude of global poverty, and the magnitude of global wealth. I feel it's important to practice [message discipline](https://en.wikipedia.org/wiki/Message_discipline) on this question, and not be distracted by side arguments about every single dollar.
2. I felt it diminished the user experience by causing the reader to pause frequently and travel down long rabbit holes, when I really want them to stay focused on the central argument.
3. It was incredibly time consuming to write and maintain this document, and was stopping me from publishing an otherwise finished product.
