### ISSUE TITLE
Add estimated "time to scroll to end" as last message

### ISSUE THREAD

**Issue by ethangodt** [MKorostoff/1-pixel-wealth#33]
It might be illustrative to add dynamic content as a last message that tells the user how much longer they'd have to scroll at their current rate to reach the end.

It took me 5-10 min to read and interact with each message. It could be powerful to know "at the rate you've been scrolling, it will take another 30-40 minutes to scroll to the end of this block of wealth".

It would be straightforward Javascript to write based on the load time of the page, and their current scroll position. I'd be happy to make a PR if you were interested.

**Comment by MKorostoff** [comment]
Thanks for the suggestion, but I am not interested in this feature. The visualization is effective precisely _because_ it allows you to experience these numbers, rather than just picture them as some hypothetical in your head.  The emotional impact comes from 1) your intuitive expectation of how large these numbers are and 2) having that expectation repeatedly broken when the scrolling just won't end.  If we prime the user's expectations with the true duration, they never get to have their expectations broken, and the experience is diminished.

**Comment by ethangodt** [comment]
Just in case it’s not clear, I’m suggesting that this only be done as the
very last message in the blue.

I dont believe people are scrolling endlessly through the blue at the end
with no prompts, but that’s a guess. I first saw this on desktop, and
grabbed the scroll bar once the messages stopped to see if anything was
left. Not to mention the scroll bar itself, which on both mobile and
desktop shows exactly how much is left (and on mobile the speed of
scrolling changes as you swipe faster distorting the effect).
