### ISSUE TITLE
Data sources and references

### ISSUE THREAD

**Issue by jccurtis** [MKorostoff/1-pixel-wealth#40]
First off, fantastic work on this. Graphics speak volumes. One comment from sharing this around with colleagues and friends has been interest in data sources for some of the metrics like:

* Annual cost of health care for a family of four
* Annual cost of chemotherapy for all cancer patients
* Annual cost to house every single homeless veteran.
* etc ...

Other referenced articles are linked for the discussion of wealth inequality but the "familiar" metrics are missing data sources / resources.

Thanks for putting this together!

**Comment by MKorostoff** [comment]
This has been requested a lot, so I've finally decided to add a [source list to the readme](https://github.com/MKorostoff/1-pixel-wealth#select-sources). That said, I am little hesitant about engaging too much with the "you got a source on that?" crowd. Here is my reasoning:

First, most of this material is trivially googleable, and the things that are _not_ trivial to research are already linked on the website. I provide inline citations already for eleven separate assertions, and only a small minority of easily located statistics are left uncited. For instance, regarding your friends who want to know the annual cost of health care for a family of four. I'm not trying to be rude here, but this is literally what happens when you google that exact phrase:

<img width="433" alt="healthcare" src="https://user-images.githubusercontent.com/1197335/85578064-c6873f00-b607-11ea-9384-3f80830d4ea2.png">

Very often, someone going "got a source on that?" is not motivated by sincere intellectual curiosity, but is instead already resolved to finding the "flaw" in any source delivered to them. Not everyone is like this of course. In fact some have the exact opposite motivation—they are hoping to bolster an argument they already agree with by fleshing it out with citations. In either case though, nothing is gained by the citation. Those who already agree will not suddenly agree _more_. Those looking for an argument will never be persuaded by any information, and are not worth engaging.

Second, to the extent that you _can_ find a flaw in some of these numbers, it almost never matters in the larger picture.  For instance, in this project I used $24,000 as the annual cost of health care for a family of four. Now, let's suppose that number is WILDLY off base. Here's how the graphic would look with a few different numbers:

<img width="716" alt="24" src="https://user-images.githubusercontent.com/1197335/85580230-8cb73800-b609-11ea-9451-c74bc8398291.png">
<img width="717" alt="28" src="https://user-images.githubusercontent.com/1197335/85580232-8cb73800-b609-11ea-879b-62bbb28287a0.png">
<img width="715" alt="8" src="https://user-images.githubusercontent.com/1197335/85580233-8cb73800-b609-11ea-8309-72cb194ae903.png">
<img width="716" alt="100" src="https://user-images.githubusercontent.com/1197335/85580234-8cb73800-b609-11ea-82a7-aadc0b3a6ccd.png">

Do you see how unimportant this distinction is in context? In some cases, the difference is so small that it's literally physically impossible for certain computer monitors to display it. Even if the number was off by 400%, the overall conclusion is exactly the same: the greatest financial burden in your life, a lifesaving resource inaccessible to millions, is in fact a tiny pebble in a grand ocean of virtually limitless wealth, and it has been denied to you through monstrous greed.

I am reminded here of [The Story of Mankind](https://en.wikipedia.org/wiki/The_Story_of_Mankind) which begins:

> High up in the North in the land called Svithjod, there stands a rock. It is a hundred miles high and a hundred miles wide. Once every thousand years a little bird comes to this rock to sharpen its beak. When the rock has thus been worn away, then a single day of eternity will have gone by.

The debate a lot of people seem to want is whether the bird ACTUALLY lands more like once every 920 years. This is such a comical missing of the point that I don't know how I could even converse with a person who thinks that way. Every single number on this page could be wrong by 3x and it _wouldn't matter at all_. The policy conclusions about taxation and poverty would still be exactly the same. But again, the numbers are _not_ wrong and anything that is even slightly debatable is already cited.

A lot of these numbers are forecasts, and therefore imprecise by their nature. Take the thing about the annual cost to house every homeless veteran. I calculate this at around half a billion, and I just added a citation in the readme. But it's still a guess. On the one hand, it might be way too high, because I'm making the probably false assumption that every single veteran needs every single dollar of their housing covered into perpetuity and will never pay any of it back. On the other hand, it might be too low, because it assumes that we'd only have to cover the cost of housing for currently homeless vets, and that this population will never grow.

There's a ton of other uncertainty factors that I'm glossing over, but long story short, this number is a projection, not a fact. Does it matter though? I could spend hours and hours writing a comprehensive guide to all the nuances and uncertainty surrounding each claim, and introduce a clunky UI that interrupts the user with footnotes every twenty seconds (in fact, [I did do that](https://github.com/MKorostoff/1-pixel-wealth/issues/3#issuecomment-621573036), and I deleted it because it was awful) but what would be gained?

Most of all, I feel these exact number debates are a massive distraction from the central thesis. Billionaire defenders will criticize any number I give no matter how rigorously I arrived at it, hoping to discredit the whole project. Supporters will spend all of their energy trying prove the number is true. This could not be further from the conversation I want surrounding this project. Hundreds of thousands of children die each year shivering in a puddle of their own diarrhea, and the superwealthy could effortlessly wipe this evil from the earth. Let's talk about _that_. I say it would cost three percent of superwealth. Could it be six percent? Sure. Would that change anything? _Of course not_.
