### ISSUE TITLE
Jump back to specific point?

### ISSUE THREAD

**Issue by jefdaj** [MKorostoff/1-pixel-wealth#44]
This is great! I got impatient scrolling through Jeff Bezos' wealth though, the first long element you don't know will have more content in it. Then I wanted to scroll back and see what I missed. Could there be some kind of little progress ticker on the bottom like "scrolled 0.4%" so people can find their way back to the right spot?

EDIT: there is just such a ticker! I guess all I want is for it to start slightly sooner.

**Comment by MKorostoff** [comment]
Thanks for the suggestion.  Variants of this have actually been suggested once or twice before, i.e. that people might leave early because they don't know the explanatory text is coming. I don't want the text or the ticker to show any sooner, because I think it sort of spoils the reveal. The impact of this work largely comes from 1) having a certain expectation about the size of these numbers and 2) having that expectation repeatedly and dramatically broken. 

That said, there might be some virtue in a table of contents in the readme file, so that returning visitors can hop around to different sections more easily. I'd be open to a pull request to that effect, otherwise I'll probably role that feature out myself eventually.
