### ISSUE TITLE
How do you argue relocation?

### ISSUE THREAD

**Issue by deleugpn** [MKorostoff/1-pixel-wealth#55]
I LOVED the paper billionaire explanation. it's so on point and it will give me ammo to not shut up when faced with liquidity issue of corporate stocks.
However, midway through the trillion ruler there's a sentence that says that the only thing that stop "us" is political will. I am interpreting "us" there as Americans and I would like to understand the perspective of how a political decision could be effective. Wouldn't 400 most rich people just cascade down any affected wealth down to their employees and/or move money overseas into any place that would prevent them from losing their money?

**Comment by MKorostoff** [comment]
> cascade down any affected wealth down to their employees and/or move money overseas
 
These are actually two separate arguments, so I'll deal with them individually. The first is what I call "the job creators" argument and the second is what I call "the capital flight" argument.

# The Capital Flight Argument

Let me start by asking a question: why does Jeff Bezos—right now, today—not move his money to Bermuda, where there is no tax? The answer is pretty simple: his money is almost all invested in Amazon, which is incorporated in America and traded on an American stock exchange. To move his money to Bermuda, he would need to first sell off his Amazon stake. Of course, he doesn't want to to that, because that investment is going to grow over time, and selling would mean missing out on _a lot_ of future income. He would miss out on more income than he would save through tax avoidance.

This is the simple reason billionaires don't generally move their cash, investments, or citizenship outside of the United States, and probably still wouldn't, even under a larger tax burden—there's money to be made by doing business in America, and that means keeping money in America, and that means paying taxes in America. On a smaller scale, why don't _you_ move your money to Bermuda? _Because your job is here_.

The other reason he wouldn't do this is that it's [illegal](https://www.investopedia.com/articles/managing-wealth/042916/offshore-banking-isnt-illegal-hiding-it.asp). You can have foreign accounts and investments, sure, but you have to report them. The US requires you to pay tax on all income, foreign or domestic, and concealing foreign income is a crime. He could maybe get around this by renouncing his citizenship, but that of course comes with the downside that he would likely need to physically leave the United States.

# The Job Creators Argument

It's easy to conflate rich people with the companies they often own or manage, but the two are not synonymous. Rich people don't just create jobs out of the ether from their personal fortune. _Businesses_ create jobs in response to consumer demand, period full stop. When consumer spending is high, businesses will add jobs to meet the demand, simple as that. When the poor and middle class have money to spend, they will spend it, and that spending is the thing that creates jobs.

We can see this intuitively in our private lives. Think about any job you've ever worked. What caused them to hire? Guaranteed the answer is "we got really busy" and not "the boss got a tax cut." We have been hearing for generations that tax cuts for the rich would lead to job growth, and watched as one administration after the next robbed our treasury to do just that, never with anything to show for it other than the smug satisfaction of billionaires.

There's a [famous apocryphal story](https://quoteinvestigator.com/2011/11/16/robots-buy-cars/) that illustrates this point. The union leader Walter Reuther was on a tour of a Ford factory with the factory management. The factory management pointed to some newly installed robots, and remarked "good luck getting them to join the union." Reuther's biting reply: "good luck getting them to buy cars." This is the point: consumer spending creates jobs, and when billionaires take all the money, it means consumers have less to spend. Less spending, less jobs, always.

And if you don't find this persuasive enough, then we have one final piece of evidence: [we just ran the policy experiment](https://en.wikipedia.org/wiki/Kansas_experiment)! The state of Kansas made a multi-billion dollar sacrifice at The Holy Church of the Sacred Job Creators in 2012, decreeing (basically) that no business owner should have to pay any taxes. The results? Declining government revenue and, ironically but unsurprisingly, declining job growth. They repealed it in in 2017.
