### ISSUE TITLE
80% vanishing point

### ISSUE THREAD

**Issue by mustyoshi** [MKorostoff/1-pixel-wealth#63]
If the wealth is held in stocks and bonds and such, wouldn't it imply that if 80% of it vanished while trying to liquidate it, that the broad market also drops by 80%?

**Comment by MKorostoff** [comment]
I don't think it matters, because it's a thing that won't happen. But for the sake of argument, I would not expect a market drop brought about by a big sell off to permanently depress the market. The price goes down when the supply is high. Once the supply is bought up, the price should rise again.

I'm not really interested in hypotheticals within hypotheticals within counterfactuals though. In the real world, this money can be liquidated. Selling an asset does not destroy the asset.
