### ISSUE TITLE
Capitalism Super Bug! 

### ISSUE THREAD

**Issue by rdwnsjjd** [MKorostoff/1-pixel-wealth#72]
It is a huge bug of Capitalism!
and there is no solution for it, at least so far!

This problem is not exists in Islam!
in Islam persons who has extra money on each end of each year, he should pay 20% of it to in need people! (calling `Khoms` means one fifth).
because this is a principle in Islam that: your money is not for you, but a leading from God and he has entrusted it to you to serve his servants with it.

there are some other ways to control wealth of persons  in Islam but with less generality like `Zakat`. but all these is on base of this belief that all of your money is not for your self, it's a lending!

**Comment by MKorostoff** [comment]
Here are some photos of the Sultan of Brunei (net worth $28 billion) riding in his gold car to his gold airplane. The median household in his country lives on $27 per day.

![maxresdefault2](https://user-images.githubusercontent.com/1197335/139682396-eab93c36-0c19-4c9c-bdbe-049f40c5dfbb.jpeg)

![maxresdefault](https://user-images.githubusercontent.com/1197335/139682406-f9db2f67-ef7a-4aa6-9d4c-e8af0c471369.jpeg)

Here is one of the many homes owned by saudi royals (net worth $1 trillion). The country has a poverty rate of 20% and is home to 61,000 slaves.

![_99253023_chateaulouisxiv](https://user-images.githubusercontent.com/1197335/139683034-382d6846-02ac-4756-89e7-aa19266a60d4.jpeg)

**Comment by rdwnsjjd** [comment]
I do not find any contradiction in your words with mine.  
First of all, none of the countries you mentioned are governed by Islamic law.  Their basic laws all is based on capitalism and liberalism.  I thought it was clear that I meant laws that were really based on Islam!  
By the way, ‌THIS IS A LAW IN ISLAM. ok, when you do not follow the law of a group, it is you who are no longer a part of that group, not that that group deviates with you!!

PS: There have always been people who have used religion for yourself illegally. A great example of that in medieval Europe! This is different from the principle of religion. I talked to you about the principle of Islam, not how people treat it.

**Comment by MKorostoff** [comment]
@rdwnsjjd Crushing poverty and inequality exist in nations of every faith, [including yours](https://carnegie-mec.org/2020/03/12/inequality-and-its-discontents-in-middle-east-pub-81266). This is most obscenely and clearly shown in the governance of Saudi Arabia which is [absolutely a theocracy](https://en.wikipedia.org/wiki/Legal_system_of_Saudi_Arabia). The suggestion that that nation is governed by "capitalism and liberalism" is just wrong and totally beyond debate. Yours is basically a [No True Scotsman](https://en.wikipedia.org/wiki/No_true_Scotsman) argument that requires us to ignore all contradicting evidence because that evidence, by definition, is not a "true" representation of your faith.
