### ISSUE TITLE
Feature request: allow translations

### ISSUE THREAD

**Issue by hmijail** [MKorostoff/1-pixel-wealth#8]
I had to find my way here to volunteer writing a Spanish translation. So please make it easier to find you back and to volunteer :)
Great job, by the way!

**Comment by MKorostoff** [comment]
Translations would be great! You can make a fork of this repository and change the text right in the browser. Once you publish on GitHub pages I'll link to it on the original.

**Comment by Celestou1818** [comment]
Starting a French translation, if anyone is keen to help with coding let me know, I can just deal with the data

**Comment by EatTheRichTextFormat** [comment]
I think it would be nice to separate content from HTML (so translators don't have to bother with HTML, and translations can benefit from future updates) and will try to code a mockup of how this could work.

**Comment by PauloQuerido** [comment]
I'm going to translate this to european portuguese. There is a good brasilian portuguese translation already, but we treat some number differently. 1 billion is 1 bilhão in Brazil but 1.000 milhões (1.000 millions) in Portugal.

**Comment by jhoon** [comment]
Already added a Spanish-translated version on #14, which is using static files on another structure, but will definitely help if you decide on going the separate translated files route.

The jquery approach is great @EatTheRichTextFormat, but I think it'll be up to @MKorostoff to decide whether to use another strategy for this -using a generator engine would be great, though.

**Comment by EatTheRichTextFormat** [comment]
No jquery used, just plain JS :smile: But I agree, it's up to @MKorostoff, I just wanted to make a proof of concept and got a little carried away. I'm willing to go the generator -> static files route if that's what he decides. One of the neat things about separating the content from the HTML is that it's actually not that hard to make the switch.

**Comment by hmijail** [comment]
@jhoon , I bow out then from the Spanish translation - I am not a web dev and surely I'd be slower doing this. (I'll keep watching in case I can help anyway)

**Comment by MKorostoff** [comment]
If you'd like to make a translation, you should do the following:

1. [Create a fork of the repo](https://help.github.com/en/github/getting-started-with-github/fork-a-repo)
2. [Edit the file index.html](https://help.github.com/en/github/managing-files-in-a-repository/editing-files-in-your-repository) to replace the english text with your preferred language. 
3. Publish your work with [github pages](https://help.github.com/en/github/working-with-github-pages/creating-a-github-pages-site). 

I'll be happy to link to your translated version from the original. If you have knowledge of web development, you can also clone the repository and fundamentally alter the content to be more relevant to your country, since this is very US centric.

I am not going to merge translations back into this repository for the following reasons:

1. I do not want to become a bottle neck or in any way constrain the creativity of volunteer translators. A lot of people have reached out to me about translations, I've actually lost count of the number. Some want to make local versions about wealthy people in their country, some just want to do a word-for-word translation of the original. I support both of these ideas, and I want everyone to be totally free to translate or restructure the page as they see fit, without worrying about compatibility with a master template.
2. I do not want to take editorial and/or legal responsibility for content I did not author in a language I do not speak. I've chosen all of my words very carefully in this project to ensure maximum factual accuracy and avoid [libelous](https://www.law.cornell.edu/wex/libel) assertions. I can't guarantee a volunteer translator will do the same. You can publish any content you like, but I am not going to put my name on it, especially if I cannot read the language it's written in.
3. Adding translation probably demands some technical solution to accommodate language switching—either at build time, or through client side rendering, both of which were discussed earlier in this thread. This would instantly transform this page from a flat, plain HTML file anyone can understand and edit into an advanced web application only comprehensible to professionals. Not only does this exclude a huge portion of people who otherwise could have participated in translation, but it also makes the page way more annoying for me personally to maintain. This project follows the philosophy of [mf webpage](https://motherfuckingwebsite.com/), now and forever. I do want an npm install, a babel transpile, or scss compile. I do not want a content abstraction layer, a front end framework, or client side rendering. I want plain HTML, period. That said, if you _do_ want some of these features, I say go for it. Fork the repo and get as advanced as you like, I won't be offended by this, and I'll be excited to see what you've built.

**Comment by sherpanat** [comment]
@Celestou1818 if you are still interested I would like to create a french adaptation.
I've forked the existing french translation https://github.com/sherpanat/1-pixel-wealth

I can handle the coding part, just looking for someone to help me with the French data to replace :)
